language: ruby
rvm:
  - 2.3.3

branches:
  only:
    - master

before_script:
  - chmod +x ./script/cibuild

script: ./script/cibuild

exclude: [vendor]
sudo: false

env:
  global:
    - GH_REF: github.com/jonatasleon/blog.git
