# Site
title:              Jonatas Leon
bio:                'Software Development'
locale:             pt_BR
baseurl:            /blog
url:                http://jonatasleon.com
description: >-
  Blog pessoal sobre programação, tecnologia, a vida, o universo e tudo mais.
logo:               'assets/img/profile.jpg'
background:         'assets/img/placeholder-big.jpg'

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   jonatasleon

# Social
twitter_username:   jonatasleon
github_username:    jonatasleon
google:
    analytics:      UA-29437560-1
email:              me@jonatasleon.com
twitter:            jonatasleon
github-url:         jonatasleon
linkedin:           jonatasleon
medium:             '@jonatasleon'

# Gems
plugins:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jemoji

# Exclude List
exclude:
  - _site
  - CNAME
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - LICENSE
  - node_modules
  - package.json
  - Rakefile
  - README.md
  - src
  - vendor
